/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------

 */
 if not exists (select 1 from [$(ECommercePlatforms)]) begin
   INSERT INTO [$(ECommercePlatforms)] (ep_name, ep_scm, ep_platform, ep_website)
    VALUES
    ('nopCommerce', 'https://github.com/nopSolutions/nopCommerce', 'dotnet','https://www.nopcommerce.com/'),
    ('Virto Commerce', 'https://github.com/VirtoCommerce/vc-platform', 'dotnet', 'https://virtocommerce.com/'),
    ('SmartStore.NET', 'https://github.com/smartstoreag/SmartStoreNET', 'dotnet', 'https://www.smartstore.com/'),
    ('GrandNode', 'https://github.com/grandnode/grandnode', 'dotnet', 'https://grandnode.com/'),
    ('Orckestra Commerce', 'https://github.com/Orckestra/C1-CMS-Foundation', 'dotnet', 'https://www.orckestra.com/'),
    ('Magento', 'https://github.com/magento/magento2', 'PHP', null),
    ('PrestaShop', 'https://github.com/PrestaShop/PrestaShop', 'PHP', null),
    ('OpenCart', 'https://github.com/opencart/opencart', 'PHP', null),
    ('AbanteCart', 'https://github.com/abantecart/abantecart-src', 'PHP', null),
    ('Pimcore', 'https://github.com/pimcore/pimcore', 'PHP', null),
    ('Akeneo', 'https://github.com/akeneo/pim-community-dev', 'PHP', null)
end

if not exists (select 1 from [$(FiatCodes)]) begin
INSERT INTO [$(FiatCodes)](fc_symbol,fc_iso_code,fc_name,fc_gdp)
VALUES
(N'د.إ', 'AED', 'United Arab Emirates dirham', 31),
(N'؋', 'AFN', 'Afghan afghani', 98),
(N'L', 'ALL', 'Albanian lek', 103),
(N'֏', 'AMD', 'Armenian dram', 139),
(N'ƒ', 'ANG', 'Netherlands Antillean guilder', null),
(N'Kz', 'AOA', 'Angolan kwanza', 56),
(N'$', 'ARS', 'Argentine peso', 25),
(N'$', 'AUD', 'Australian dollar', 14),
(N'ƒ', 'AWG', 'Aruban florin', null),
(N'₼', 'AZN', 'Azerbaijani manat', 56),
(N'KM', 'BAM', 'Bosnia and Herzegovina convertible mark', null),
(N'$', 'BBD', 'Barbados dollar', null),
(N'৳', 'BDT', 'Bangladeshi taka', 39),
(N'лв', 'BGN', 'Bulgarian lev', 70),
(N'د.ب', 'BHD', 'Bahraini dinar', 48),
(N'₣', 'BIF', 'Burundian franc', 190),
(N'$', 'BMD', 'Bermudian dollar', null),
(N'$', 'BND', 'Brunei dollar', null),
(N'Bs.', 'BOB', 'Boliviano', 84),
(N'$BOV', 'BOV', 'Bolivian Mvdol (funds code)', null),
(N'R$', 'BRL', 'Brazilian real', 9),
(N'$', 'BSD', 'Bahamian dollar', null),
(N'Nu.', 'BTN', 'Bhutanese ngultrum', null),
(N'P', 'BWP', 'Botswana pula', 131),
(N'Br.', 'BYN', 'Belarusian ruble', 69),
(N'$', 'BZD', 'Belize dollar', null),
(N'$', 'CAD', 'Canadian dollar', 10),
(N'₣', 'CDF', 'Congolese franc', 116),
(N'Che', 'WIR', 'WIR euro (complementary currency)', null),
(N'Fr.', 'CHF', 'Swiss franc', 20),
(N'Che', 'WIR', 'WIR franc (complementary currency)', null),
(N'UF', 'CLF', 'Unidad de Fomento (funds code)', null),
(N'$', 'CLP', 'Chilean peso', 41),
(N'$', 'COP', 'Colombian peso', 34),
(N'URV', 'COU', 'Unidad de Valor Real (UVR) (funds code)[6]', null),
(N'₡', 'CRC', 'Costa Rican colon', 79),
(N'$', 'CUC', 'Cuban convertible peso', null),
(N'$', 'CUP', 'Cuban peso', null),
(N'$', 'CVE', 'Cape Verdean escudo', null),
(N'Kč', 'CZK', 'Czech koruna', 49),
(N'₣', 'DJF', 'Djiboutian franc', null),
(N'kr.', 'DKK', 'Danish krone', 17),
(N'RD$', 'DOP', 'Dominican peso', 64),
(N'د.ج', 'DZD', 'Algerian dinar', 45),
(N'ج.م', 'EGP', 'Egyptian pound', 39),
(N'ናቕ', 'ERN', 'Eritrean nakfa', null),
(N'Br.', 'ETB', 'Ethiopian birr', 70),
(N'€', 'EUR', 'Euro', 2),
(N'$', 'FJD', 'Fiji dollar', null),
(N'£', 'FKP', 'Falkland Islands pound', null),
(N'£', 'GBP', 'Pound sterling', 4),
(N'ლ', 'GEL', 'Georgian lari', 124),
(N'₵', 'GHS', 'Ghanaian cedi', 60),
(N'£', 'GIP', 'Gibraltar pound', null),
(N'D', 'GMD', 'Gambian dalasi', null),
(N'FG', 'GNF', 'Guinean franc', 124),
(N'Q', 'GTQ', 'Guatemalan quetzal', 69),
(N'$', 'GYD', 'Guyanese dollar', null),
(N'$', 'HKD', 'Hong Kong dollar', 36),
(N'L', 'HNL', 'Honduran lempira', 119),
(N'G', 'HTG', 'Haitian gourde', null),
(N'Ft', 'HUF', 'Hungarian forint', 55),
(N'Rp', 'IDR', 'Indonesian rupiah', 16),
(N'₪', 'ILS', 'Israeli new shekel', 33),
(N'₹', 'INR', 'Indian rupee', 3),
(N'ع.د', 'IQD', 'Iraqi dinar', 59),
(N'﷼', 'IRR', 'Iranian rial', 29),
(N'kr.', 'ISK', 'Icelandic króna (plural: krónur)', 146),
(N'J$', 'JMD', 'Jamaican dollar', null),
(N'JD', 'JOD', 'Jordanian dinar', 97),
(N'¥', 'JPY', 'Japanese yen', 3),
(N'KSh', 'KES', 'Kenyan shilling', 65),
(N'лв', 'KGS', 'Kyrgyzstani som', 113),
(N'៛', 'KHR', 'Cambodian riel', 144),
(N'CF', 'KMF', 'Comoro franc', null),
(N'₩', 'KPW', 'North Korean won', null),
(N'₩', 'KRW', 'South Korean won', 11),
(N'د.ك', 'KWD', 'Kuwaiti dinar', 53),
(N'$', 'KYD', 'Cayman Islands dollar', null),
(N'〒', 'KZT', 'Kazakhstani tenge', 48),
(N'₭', 'LAK', 'Lao kip', null),
(N'£', 'LBP', 'Lebanese pound', 58),
(N'Rs.', 'LKR', 'Sri Lankan rupee', 71),
(N'$', 'LRD', 'Liberian dollar', null),
(N'L', 'SLL', 'Leone (old leone)[15]', null),
(N'Sh.', 'SOS', 'Somali shilling', 131),
(N'$', 'SRD', 'Surinamese dollar', null),
(N'£', 'SHP', 'Saint Helena pound', null),
(N'Le', 'SLL', 'Leone (new leone)', null),
(N'S', 'R', 'South African rand', 13),
(N'?', 'SDG', 'Sudanese pound', null),
(N'kr.', 'SEK', 'Swedish krona (plural: kronor)', 24),
(N'$', 'SGD', 'Singapore dollar', 37),
(N'£', 'SLE', 'Sierra Leonean leone (new leone)', null),
(N'Le', 'SLL', 'Sierra Leonean leone (old leone)', null),
(N'Sh.', 'SCR', 'Seychelles rupee', null),
(N'£', 'GBP', 'Saint Helena pound', null),
(N'£', 'SHP', 'Saint Helena pound', null),
(N'Le', 'SLL', 'Sierra Leonean leone (new leone)', null),
(N'?', 'SOS', 'Somali shilling', 131),
(N'$', 'SRD', 'Surinamese dollar', null),
(N'£', 'SSP', 'South Sudanese pound', null),
(N'Db.', 'STN', 'São Tomé and Príncipe dobra', null),
(N'₡', 'SVC', 'Salvadoran colón', 122),
(N'£', 'SYP', 'Syrian pound', 109),
(N'฿', 'THB', 'Thai baht', 25),
(N'SM', 'TJS', 'Tajikistani somoni', 143),
(N'm', 'TMT', 'Turkmenistan manat', 121),
(N'د.ت', 'TND', 'Tunisian dinar', 88),
(N'$', 'TOP', 'Tongan paʻanga', null),
(N'$', 'TWD', 'New Taiwan dollar', 30),
(N'TSh', 'TZS', 'Tanzanian shilling', 38),
(N'₴', 'UAH', 'Ukrainian hryvnia', 45),
(N'$', 'USD', 'United States dollar', 1),
(N'$', 'UYU', 'Uruguayan peso', 57),
(N'$U', 'UYI', 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)', null),
(N'Bs.F.', 'VEF', 'Venezuelan bolívar', 126),
(N'₫', 'VND', 'Vietnamese đồng', 36),
(N'Vt.', 'VUV', 'Vanuatu vatu', null),
(N'WS$', 'WST', 'Samoan tala', null),
(N'﷼', 'YER', 'Yemeni rial', 118),
(N'ZK', 'ZMW', 'Zambian kwacha', 102),
(N'$', 'ZWD', 'Zimbabwean dollar A/10', null)


COMMIT;
end
